// The package version, copied into the source so the library can report it.
//
// THERE IS ONE VERSION AND IT LIVES IN package.json, which the release workflow
// writes from the release tag. This script derives the source constant from it;
// the generated file is not committed and must never be edited by hand, so the
// two cannot drift apart.
//
// It runs after install and before every build, test, type check and lint, so a
// fresh clone and an editor both see the file without anyone having to know it
// is generated.
import { readFile, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const packageRoot = dirname(dirname(fileURLToPath(import.meta.url)))

const manifest = JSON.parse(await readFile(join(packageRoot, 'package.json'), 'utf8'))
const { version } = manifest
if (typeof version !== 'string' || version === '') {
  throw new Error('package.json carries no version')
}

const source = `// GENERATED by scripts/write-version.mjs. Do not edit, and do not commit.
//
// The single source of the version is package.json, which the release workflow
// writes from the release tag.

/** The version of this package. */
export const SDK_VERSION = '${version}'
`

await writeFile(join(packageRoot, 'src/internal/version.ts'), source)
